### ISSUE TITLE
[Bug]: Themes change incorrectly

### ISSUE THREAD

**Issue by brandonzorn** [zhiyiYo/PyQt-Fluent-Widgets#931]
### What happened?

when switching between light and dark themes in windows, the themes in pyqtfluentwidgets change incorrectly

https://github.com/user-attachments/assets/4e339ce7-46aa-4083-9c51-4ad0903b6e0e

### Operation System

Windows11 23H2

### Python Version

PyQtFluentWidgets Pro Gallery

### PyQt/PySide Version

PyQtFluentWidgets Pro Gallery

### PyQt/PySide-Fluent-Widgets Version

1.6.0

### How to Reproduce?

 1. Set dark theme in windows
 2. Launch PyQtFluentWidgets Pro Gallery
 3. Set dark theme in PyQtFluentWidgets Pro Gallery
 4. Change theme to light in windows

### Minimum code

```python3
-
```

**Comment by mengdeer589** [comment]
我也遇到了类似的问题，但不是在切换window主题的时候，使用setTheme函数的时候，qfluentwidget的tableview组件，主题色切换出现了像上面视频中那种异常白色

**Comment by dy0gu** [comment]
Why is this issue closed? I'm still getting it on the latest version.

The worst part is it's impossible to pinpoint where it's coming from, I reverted to a previous commit where the theme change was working fine and it also doesn't work there anymore!

**Comment by zhiyiYo** [comment]
It's a bug of windows os. You can close the mica effect to avoid this problem

**Comment by dy0gu** [comment]
Hey @zhiyiYo , thanks for your reply.

My problem was in fact another, and everything works fine now, even with the mica effect!

This was the _bad_ piece of code:

```python
class Options(QConfig):
    """Global object for app options."""

    country = OptionsConfigItem("App", "locale", QLocale.Country.UnitedStates,
                               OptionsValidator(QLocale.Country), EnumSerializer(QLocale.Country), restart=True)

    language = OptionsConfigItem("App", "language", QLocale.Language.English,
                                OptionsValidator(QLocale.Language), EnumSerializer(QLocale.Language), restart=True)
    themeMode = OptionsConfigItem("Window", "themeMode", qfluentwidgets.Theme.DARK,
                                OptionsValidator(qfluentwidgets.Theme), EnumSerializer(qfluentwidgets.Theme), restart=True)
    themeColor = OptionsConfigItem("Window", "themeColor", "#2BA9ED",
                                   ColorValidator(qfluentwidgets.QColor()), ColorSerializer(), restart=True)
customizable = Options()
customizable.themeMode.valueChanged.connect(lambda theme: (qfluentwidgets.setTheme(theme),
                                                       logging.info(f"Theme mode set to {theme.value}")))
customizable.themeColor.valueChanged.connect(lambda color: (qfluentwidgets.setThemeColor(color),
                                                       logging.info(f"Theme color set to {color}")))
qconfig.load('config/config.json', customizable)
```

I followed the [Configuration](https://qfluentwidgets.com/pages/components/config/#usage) docs and wanted to manually handle the saving of ThemeMode and ThemeColor, because I dislike having the save "magic" hidden behind the library functions. That is where the problems began.

When your `setTheme` function was called it was causing some weird logic to overlap because you also use `qconfig.themeMode` here:

```python
def setTheme(theme: Theme, save=False, lazy=False):
    """ set the theme of application

    Parameters
    ----------
    theme: Theme
        theme mode

    save: bool
        whether to save the change to config file

    lazy: bool
        whether to update the style sheet lazily, set to `True` will accelerate theme switching
    """
    qconfig.set(qconfig.themeMode, theme, save)
    updateStyleSheet(lazy)
    qconfig.themeChangedFinished.emit()
```

I tried to fix it by disabling your saving but for some reason calling `setTheme(save=False)` still saves to the config file:
```json
{
    "QFluentWidgets": {
        "ThemeColor": "#ff009faa",
        "ThemeMode": "Dark"
    }
}
```

It would probably be nice to add into the [Configuration ](https://qfluentwidgets.com/pages/components/config/#usage) documentation that there are some keys reserved by the library that can cause issues if reused.

As of now I haven't found a way to manually handle the saving without getting issues one way or another. It would be great if this "magic" could be handled by ourselves and the theme logic isolated from the QConfig object.

Other then that I'm loving it, thank you for a great package!
